### ISSUE TITLE
Need for collateralization of ERC-721 NFTs

### ISSUE THREAD

**Issue by kggp1995** [dharmaprotocol/charta#144]
Me & my partner @aj07 from ETHIndia are working on enhancement to Dharma in collateralizing the ERC-721 assets such as NFTs, derivatives & dear collectibles such as cryptokitties!

Here's an early scratch we are working on - https://github.com/LendnMake/lendnmake-contracts

Cc @nadavhollander @graemecode 

EDIT: Closed the issue https://github.com/dharmaprotocol/relayer-kit/issues/22 from `Relayer-kit` repo

**Comment by graemecode** [comment]
Just merged https://github.com/dharmaprotocol/charta/pull/145
