### ISSUE TITLE
RFC: Extract Collateralized from Inheritance Hierarchy

### ISSUE THREAD

**Issue by graemecode** [dharmaprotocol/charta#54]
### Overview
Here we propose extracting collateralized from the inheritance hierarchy, to avoid multiple-inheritance downstream. The extracted functions will exist in its own contract with storage.

### Rationale
Multiple inheritance in Solidity can cause bugs if the programmer is not cautious (c.f. https://pdaian.com/blog/solidity-anti-patterns-fun-with-inheritance-dag-abuse.) Charta should avoid any patterns that allows users to create contracts with bugs due to a slight oversight - such as misunderstanding c3 linearization in Solidity.

### Alternatives
* Keep the current implementation, using multiple inheritance, which will allow us to ship faster, but could be problematic down the line.
* Implement the collateralization functionality as a library. 

### Engineering Implementation
* Create a contract Collateralizer.sol that implements the following public functions
	* registerTermStart
		* Only called by debt kernel; called upon debt agreement’s issuance
		* Checks necessary preconditions, such as token balances
		* Pulls collateral from the debtor to the custodian
		* Emits an event that the collateral has been secured
	* returnCollateral
		* Returns collateral to the original debtor, iff debt terms has lapsed and expected repayment has been made.
		* Emits an event that the collateral has been returned
	* SeizeCollateral
		* Takes collateral from the debt agreement and transfers it to the beneficiary who owns the debt
		* Emits an event that the collateral has been seized
	* Uses the following storage
		* debtKernalAddress (for validating that only the debt kernel can call certain functions)
		* debtRegistry, tokenRegistry
		* agreementToCollateralizer, a mapping of the agreement id to the address of the collateralizer

**Comment by nadavhollander** [comment]
Thanks for putting this together @graemecode -- this is super valuable.

Totally on board with separating this out into its own contract -- the only part I find problematic is having `registerTermStart` be a part of the `Collateralizer.sol` contract.

Currently, `registerTermStart` is called by the DebtKernel on whatever `TermsContract` is associated with the currently issued debt agreement.  By porting `registerTermStart` into the  Collateralizer contract, we either need to create special cases in the `DebtKernel` contract, or have to treat the Collateralizer contract as a terms contract (which would defeat the intention of this RFC).  More logical, IMO, is having a `collateralize` function that can only be called by an approved list of terms contracts (we can use `PermissionsLib` for this).  That way, `registerTermStart` would remain in `Simple|CompoundInterestTermsContract`, and would in turn call `Collateralizer.sol`.

Thoughts?

**Comment by graemecode** [comment]
@nadavhollander Good call. Merged with https://github.com/dharmaprotocol/charta/pull/64
